name: Build

on:
  push:
    paths-ignore:
      - "**.md"
      - "examples/**"
    branches:
      - main

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            ghcr.io/${{ github.repository_owner }}/devcontainer:buster

  build-node-ruby:
    name: Build devcontainer with node and ruby installed
    needs: build-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16.14.0", "14.19.0", "12.22.10"]
        ruby: ["3.1.1", "3.0.3", "2.7.5"]
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: ./node-ruby
          build-args: |
            BASE_TAG=buster
            NODE_VERSION=${{ matrix.node }}
            RUBY_VERSION=${{ matrix.ruby }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/devcontainer:node-${{ matrix.node }}-ruby-${{ matrix.ruby }}-buster
