name: Build

on:
  push:
    branches:
      - main

jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags:
            ghcr.io/${{ github.repository_owner }}/devcontainer:buster-main
