name: release-features

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release-features.yml
      - features/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features"
          generate-docs: "false"
          disable-schema-validation: "true"
          disable-repo-tagging: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.FIX_GITHUB_TOKEN_TO_WRITE_PACKAGES }}
